// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import "./globals.css";

// Importar fontes do @fontsource
import '@fontsource/geist-sans/400.css';
import '@fontsource/geist-sans/500.css';
import '@fontsource/geist-sans/600.css';
import '@fontsource/geist-sans/700.css';
import '@fontsource/geist-mono/400.css';
import '@fontsource/geist-mono/500.css';

export const metadata: Metadata = {
  title: "BMD Project",
  description: "Sistema de Gestão de Construção",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="font-geist-sans antialiased">
        {children}
      </body>
    </html>
  );
}